CREATE TABLE 'user' (
	
	'OID' VARCHAR(255) DEFAULT NULL,
	'VERSION' VARCHAR(255) DEFAULT NULL,
	'USER_NAME' VARCHAR(255) DEFAULT NULL,
	'USER_CODE' VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY ('OID')	
)ENGINE=INNODB DEFAULT CHARSET=utf8